spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway-dev
    username: postgres
    password: 1qaz@WSX#EDC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  application:
    name: flyway
  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

